const frases = [
    [
        "De acordo com Schrödinger,",
        "Uma recente pesquisa demonstra que",
        "Acadêmicos debatem que",
        "Experimentos demonstram a probabilidade de que",
        "Fundamentalmente,",
        "Evidentemente,",
        "Por dedução direta,",
        "Obviamente",
        "Utilizamos o método ciêntifico para demonstrar que",
        "Como ja foi previsto na teoria da relatividade,",
        "Como antes foi dito por Einstein,",
        "A distribuição de Gauss prevê que",
        "Dado os conhecimentos adquiridos durante a história,",
        "Newton uma vez afirmou que",
        "A integral de uma função em intervalos definidos infere que",
        "Segundo o modelo padrão,",
        "Jupiter está se deteriorando, isso levou ao fato de que",
        "O objetivo desse experimento é calcular como",
        "É trivial que",
        "Segundo o teorema do virial",
        "Segundo a série de Taylor,",
        "Segundo a teoria de grupos postulada por Terence Tao,",
        "Segundo a mecânica de Laplace,",
        "Dado o desvio padrão,",
        "Segundo o teorema de Navier-Stokes,",
        "Segundo o físico Ludwig Boltzmann,",
        "A integral de Lebesgue determina que",
        "A dualidade partícula onda indica que",
        "Desprezado a resistência do ar é facil notar que"
    ],
    [
        " a crescente busca pela teoria unificada",
        " a energia cinética do objeto",
        " a derivada da função",
        " o experimento realizado",
        " a, cada vez maior, busca por respostas",
        " a necessidade de respostas sobre um determinado tópico",
        " a energia mecânica conservada", 
        " o teletransporte de matéria",
        " o valor da constante gama",
        " a amplitude do movimento",
        " a influencia dos físicos teóricos contemporâneos",
        " o zero absoluto",
        " um quark com spin 1/2",
        " o momento de inércia",
        " o empuxo criado",
        " uma integral",
        " o spin do elétron diferencial",
        " um vetor de estado",
        " a constante sensação de vazio",
        " a intrigante equação de Maxwell",
        " uma expansão livre",
        " a impossibilidade da continuidade somente pela física teórica",
        " a velocidade angular média",
        " a densidade de probabilidade",
        " a ejeção de massa coronal",
        " o tunelamento ",
        " a integração do ruído",
        " a distribuição beta",
        " um sistema massa mola",
        " a integral de caminho fechado",
        " a distribuição de velocidade de maxwell",
        " a equivalência de uma caneca a uma rosquinha",
        " a topologia",
        " o sofrimento do gato de Schrödinger",
        " a demonstração trivial"
    ],
    [
        " nos obriga à análise",
        " exige a precisão e a definição",
        " assume a continuidade",
        " é uma das consequências",
        " não pode mais se dissociar",
        " estimula a diferenciação",
        " aponta para a convergência",
        " afeta positivamente a correta previsão",
        " implica em fusão de átomos",
        " exige uma fortificação dos alicerces que servem de ferramenta",
        " é consequência",
        " oscila em n-dimensões",
        " nos leva a questionar a procedência",
        " é mais recorrente que pensávamos, e portanto leva ao questionamento",
        " é a figura chave da revolução científica",
        " é conflitante com a ideia",
        " é possível de ser visualizada num vetor de n-dimesões",
        " e, ao ser transformada em matriz de proporções n x m, dissocia a análise anterior",
        " constrói um gráfico polinomial",
        " pode ser análisado como uma expressão algébrica que se aproxima",
        " exige a análise da assimetria barionica",
        " é correspondente",
        " corresponde ao tunelamento quântico",
        " escalonando por Gauss-Jordan",
        " provoca a comunicação de átomos",
        " aumenta a energia potencial",
        " gera um avanço",
    ],
    [
        " das novas proposições.",
        " do levantamento de dados experimentais.",
        " dos métodos utilizados na avaliação de resultados.",
        " das conjecturas inferidas.",
        " da geometria euclidiana.",
        " do tempo de decaimento dos átomos.",
        " das partículas subatômicas.",
        " da posição do elétron.",
        " do modelo estabelecido.",
        " das provas por indução.",
        ", particialmente, da relatividade geral.",
        " dos transitos de informação por fótons.",
        " dos campos quânticos.",
        " da Teoria Cinética dos Gases.",
        " do gás em análise.",
        " da Teoria das Cordas.",
        " das descobertas de Isaac Newton no século XV.",
        " da escala Kelvin.",
        " de um buraco negro.",
        " de um caminho fechado.",
        " de um elipsóide.",
        " graças às descobertas de Isaac Newton no século XV.",
        " como previsto pelo astronomo Johannes Kepler.",
        " de operadores simétricos.",
        " da teria de convergencia.",
        " do gradiente da função.",
        " do teorema do valor médio.",
        " da relatividade geral de Einstein.",
        " de elétrons quantizados.",
        " do raio de convergência.",
        " de qualquer comprimento de onda",
    ]
  ];
