const frases = [
    [
        "De acordo com Schrödinger, ",
        "Uma recente pesquisa demonstra que ",
        "Acadêmicos debatem que ",
        "Experimentos demonstram a probabilidade de que ",
        "Fundamentalmente, ",
        "Evidentemente, ",
        "Por dedução direta, ",
        "Obviamente ",
        "Utilizamos o método ciêntifico para demonstrar que ",
        "Como ja foi previsto na teoria da relatividade, ",
        "Como antes foi dito por Einstein, ",
        "A distribuição de Gauss prevê que ",
        "Dado os conhecimentos adquiridos durante a história, ",
        "Newton uma vez afirmou que ",
        "A integral de uma função em intervalos definidos infere que ",
        "Segundo o modelo padrão, ",
        "Jupiter está se deteriorando, isso levou ao fato de que ",
        "O objetivo desse experimento é calcular como ",
        "É trivial que "
        
    ],
    [
        "a crescente busca pela teoria unificada ",
        "a energia cinética do objeto ",
        "a derivada da função ",
        "o experimento realizado ",
        "a, cada vez maior, busca por respostas ",
        "a necessidade de respostas sobre um determinado tópico ",
        "a energia mecânica conservada ", 
        "o teletransporte de matéria ",
        "o valor da constante gama ",
        "a amplitude do movimento ",
        "a influencia dos físicos teóricos contemporâneos ",
        "o zero absoluto",
        "um quark com spin 1/2 ",
        "o momento de inércia ",
        "o empuxo criado ",
        "uma integral ",
        "o spin do elétron diferencial ",
        "um vetor de estado "
    ],
    [
        "nos obriga à análise ",
        "exige a precisão e a definição ",
        "assume a continuidade ",
        "é uma das consequências ",
        "não pode mais se dissociar ",
        "estimula a diferenciação ",
        "aponta para a convergência ",
        "afeta positivamente a correta previsão ",
        "implica em fusão de átomos ",
        "leva a uma caneca equivaler a uma rosquinha ", 
        "exige uma fortificação dos alicerces que servem de ferramenta ",
        "tem como consequência ",
        "oscila em n-dimensões ",
    ],
    [
        "das novas proposições.",
        "do levantamento de dados experimentais.",
        "dos métodos utilizados na avaliação de resultados.",
        "das conjecturas inferidas.",
        "da geometria euclidiana.",
        "do tempo de decaimento dos átomos.",
        "das partículas subatômicas.",
        "da posição do elétron.",
        "do modelo estabelecido.",
        "das provas por indução.",
        ", particialmente, da relatividade geral.",
        "dos transitos de informação por fótons.",
        "dos campos quânticos.",
        "da Teoria Cinética dos Gases.",
        "do gás em análise.",
        "da Teoria das Cordas.",
        "graças as descobertas de Isaac Newton no século XV.",
        "da escala Kelvin.",
        "de um buraco negro.",
        "de um caminho fechado.",
        "de um elipsóide."
    ]
  ];
